---
- name: Ensure .bashrc exists
  ansible.builtin.file:
    path: "{{ ansible_facts['env']['HOME'] }}/.bashrc"
    state: touch
    modification_time: preserve
    access_time: preserve

- name: Install nvm
  ansible.builtin.shell: >
    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.4/install.sh | bash
  args:
    creates: "{{ ansible_facts['env']['HOME'] }}/.nvm/nvm.sh"

- name: Install Node.js LTS via nvm
  ansible.builtin.command:
    cmd: >
      bash -lc 'export NVM_DIR="{{ ansible_facts["env"]["HOME"] }}/.nvm";
      . "$NVM_DIR/nvm.sh";
      nvm install --lts'
